spring:
  application:
    name : event-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/event-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    encoding: UTF-8
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: 586E3272357538782F413F4428472B4B6150645367566B597033733676397924
      expiration: 604800000 # 7 day

logging:
  level:
    org:
      springframework=DEBUG:

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled=true
