-- event-db.refresh_tokens definition
DROP TABLE IF EXISTS refresh_tokens;

CREATE TABLE refresh_tokens (
    refresh_token_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    token VARCHAR(512) NOT NULL UNIQUE,
    expiry_date TIMESTAMP NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT refresh_token_pkey PRIMARY KEY (refresh_token_id),
    CONSTRAINT fk_user_id FOREIGN KEY(user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

-- Adding indexes to optimize lookups
CREATE INDEX idx_user_id ON refresh_tokens(user_id);

COMMIT;
