-- event-db.users definition
DROP TABLE IF EXISTS users;

create table users (
    user_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    role VARCHAR(50) NOT NULL CHECK (role IN ('ADMIN', 'MANAGER', 'PARTICIPANT')),
    CONSTRAINT user_pkey PRIMARY KEY (user_id)
);

COMMIT;

