-- event-db.sponsors definition
DROP TABLE IF EXISTS events;

CREATE TABLE events (
    event_id 			    BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    title 				    VARCHAR(100) NOT NULL,
    description 		    VARCHAR(255) NOT NULL,
    created_at 			    TIMESTAMP NOT NULL,
    start_date 			    TIMESTAMP NOT NULL,
    end_date 			    TIMESTAMP NOT NULL,
    category 		        VARCHAR(50) NOT NULL,
    price                   DECIMAL(10, 2) NOT NULL,
    user_id 		        BIGINT NOT NULL,
    event_location_id 	    BIGINT NOT NULL,
    CONSTRAINT event_pkey PRIMARY KEY (event_id),
    CONSTRAINT fk_user_id FOREIGN KEY(user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_event_location_id FOREIGN KEY(event_location_id) REFERENCES event_locations(event_location_id) ON DELETE SET NULL
);

-- Add indexes for manager_id and event_location_id for faster join queries
CREATE INDEX idx_event_manager_id ON events(user_id);
CREATE INDEX idx_event_event_location_id ON events(event_location_id);
CREATE INDEX idx_event_category ON events(category);

COMMIT;
